version: '3.3'
services:

  # https://hub.docker.com/_/mongo
  mongodb:
    image: mongo:4.2
    container_name: mongodb-primary
    hostname: mongodb-primary
    command: >
      mongod
      --port 27017
      --replSet replset
      --auth --keyFile /etc/mongod-keyfile
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: example
    volumes:
      - ./docker/mongo/scripts:/root:ro
      - ./docker/mongo/etc/mongod-keyfile:/etc/mongod-keyfile:ro
    ports:
      - 27017:27017
    networks:
      - replset
    depends_on:
      - mongodb-secondary-01
      - mongodb-secondary-02
    restart: on-failure

  # https://hub.docker.com/_/mongo
  mongodb-secondary-01:
    image: mongo:4.2
    container_name: mongodb-secondary-01
    hostname: mongodb-secondary-01
    command: >
      mongod
      --port 27018
      --replSet replset
      --auth --keyFile /etc/mongod-keyfile
    volumes:
      - ./docker/mongo/etc/mongod-keyfile:/etc/mongod-keyfile:ro # Permission: 600
    ports:
      - 27018:27018
    networks:
      - replset
    depends_on:
      - mongodb-secondary-02
    restart: on-failure

  # https://hub.docker.com/_/mongo
  mongodb-secondary-02:
    image: mongo:4.2
    container_name: mongodb-secondary-02
    hostname: mongodb-secondary-02
    command: >
      mongod
      --port 27019
      --replSet replset
      --auth --keyFile /etc/mongod-keyfile
    volumes:
      - ./docker/mongo/etc/mongod-keyfile:/etc/mongod-keyfile:ro # Permission: 600
    ports:
      - 27019:27019
    networks:
      - replset
    restart: on-failure

networks:
  replset:
    ipam:
      config:
        - subnet: 192.168.1.0/24
