# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.8]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - run: docker-compose up -d
    - run: docker-compose exec mongodb mongo admin -u root -p example /root/01_replset.js
    - run: docker-compose exec mongodb mongo admin -u root -p example /root/02_db.js
    - run: docker-compose exec mongodb mongo admin -u root -p example /root/03_user.js
    - run: yarn --frozen-lockfile
    - run: yarn build
    - run: yarn test
